#!/bin/bash -eux

imds_token="$(curl -sSfL --retry 3 -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")"
instance_id="$(curl -sSfL --retry 3 -H "X-aws-ec2-metadata-token: $imds_token" http://169.254.169.254/latest/meta-data/instance-id)"
local_ipv4="$(curl -sSfL --retry 3 -H "X-aws-ec2-metadata-token: $imds_token" http://169.254.169.254/latest/meta-data/local-ipv4)"

region='${AWS::Region}'
allocation='${ALLOCATION}'

/usr/bin/aws --region "$region" ec2 associate-address --instance-id "$instance_id" --allocation-id "$allocation" --allow-reassociation
