#!/bin/bash -eux

root_pass_file=/var/lib/mysql/persist/root-password
mm_pass_file=/var/opt/mattermost/persist/mysql-password

if [ -d /var/lib/mysql/data/mysql ]; then
  exit 0
fi

if [ -f "$root_pass_file" ]; then
  echo "Error: $root_pass_file already exists."
  exit 1
fi

if [ -f "$mm_pass_file" ]; then
  echo "Error: $mm_pass_file already exists."
  exit 1
fi

head /dev/urandom | tr -dc A-Za-z0-9_- | head -c 32 > "$root_pass_file"
chmod 400 "$root_pass_file"

head /dev/urandom | tr -dc A-Za-z0-9_- | head -c 32 > "$mm_pass_file"
chmod 400 "$mm_pass_file"
chown mm: "$mm_pass_file"

sudo -u mysql mysqld \
  --no-defaults --user=mysql \
  --datadir=/var/lib/mysql/data \
  --log-error-verbosity=3 \
  --initialize-insecure

file="$(mktemp)"
trap 'rm -f $file' EXIT

cat <<'EOF' > "$file"
%%SQL
EOF

systemctl start mysqld

# Never output password to log
set +x
root_pass="$(< "$root_pass_file")"
mm_pass="$(< "$mm_pass_file")"
sed -i "s;%ROOT_PASSWORD%;$root_pass;g" "$file"
sed -i "s;%MM_PASSWORD%;$mm_pass;g" "$file"
mysql -u root < "$file"
set -x
