FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY '%ROOT_PASSWORD%';
CREATE USER 'mm'@'localhost' IDENTIFIED BY '%MM_PASSWORD%';
CREATE DATABASE mm;
GRANT ALL ON mm.* TO 'mm'@'localhost';
FLUSH PRIVILEGES;
