from troposphere import GetAtt, Sub, cloudfront

from mattermost.common import util


def distribution(
    *, cloudfront_certificate_arn, domain, default_cache_policy,
    distribution_log_bucket):
  return cloudfront.Distribution(
      'Distribution',
      DistributionConfig=cloudfront.DistributionConfig(
          Aliases=[util.read_param(domain)],
          Comment=Sub('Generated by ${AWS::StackName}'),
          DefaultCacheBehavior=cloudfront.DefaultCacheBehavior(
              AllowedMethods=[
                  'GET',
                  'HEAD',
                  'OPTIONS',
                  'PUT',
                  'PATCH',
                  'POST',
                  'DELETE',
              ],
              CachedMethods=[
                  'GET',
                  'HEAD',
              ],
              CachePolicyId=util.name_of(default_cache_policy),
              Compress=True,
              TargetOriginId='main',
              ViewerProtocolPolicy='redirect-to-https')),
      Enabled=True,
      HttpVersion='http2and3',
      Logging=cloudfront.Logging(
          Bucket=GetAtt(distribution_log_bucket, 'DomainName'),
          IncludeCookies=False),
      Origins=[
          cloudfront.Origin(
              CustomOriginConfig=cloudfront.CustomOriginConfig(
                  OriginProtocolPolicy='https-only'),
              DomainName=Sub(
                  'origin.${AWS::StackName}.${domain}',
                  domain=util.read_param(domain)),
              Id='main'),
      ],
      ViewerCertificate=cloudfront.ViewerCertificated(
          AcmCertificateArn=util.read_param(cloudfront_certificate_arn),
          CloudFrontDefaultCertificate=False,
          MinimumProtocolVersion='TLSv1.2_2021',
          SslSupportMethod='sni-only'))
