from troposphere import GetAtt, Sub, route53

from mattermost.common import util

ALIAS_RECORD_SET_HOSTED_ZONE = 'Z2FDTNDATAQYW2'


def origin_record_set(*, domain, hosted_zone, eip):
  return route53.RecordSetType(
      'OriginRecordSet',
      Comment=Sub('Generated by ${AWS::StackName}'),
      HostedZoneId=util.read_param(hosted_zone),
      Name=Sub(
          'origin.${AWS::StackName}.${domain}', domain=util.read_param(domain)),
      ResourceRecords=[GetAtt(eip, 'PublicIp')],
      TTL=str(60 * 60),
      Type='A')
