#!/bin/bash -eux

allocation_id='${ALLOCATION}'
region='${AWS::Region}'

imds_token="$(curl -sSL -f --retry 3 -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")"
instance_id="$(curl -sSL -f --retry 3 -H "X-aws-ec2-metadata-token: $imds_token" http://169.254.169.254/latest/meta-data/instance-id)"

aws="/usr/bin/aws --region $region"

eip_assoc_id="$($aws ec2 describe-addresses \
  --allocation-ids "$allocation_id" \
  --query 'Addresses[0].AssociationId' \
  --output text)"

if [[ "$eip_assoc_id" == "None" ]]; then
  $aws ec2 associate-address \
    --instance-id "$instance_id" \
    --allocation-id "$allocation_id" \
    --no-allow-reassociation
fi
